// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedRepository() *Repository {
	studentRepository := NewStudentRepository()
	lecturerRepository := NewLecturerRepository()
	repository := NewRepository(studentRepository, lecturerRepository)
	return repository
}

func InitializedService(log bool) *Service {
	simpleDatabaseMaster := NewDatabaseMaster()
	simpleDatabaseTransaction := NewDatabaseTransaction()
	transactionRepository := NewTransactionRepository(log)
	transactionService := NewTransactionService(simpleDatabaseMaster, simpleDatabaseTransaction, transactionRepository)
	simpleDatabaseSummary := NewDatabaseSummary()
	summaryRepository := NewSummaryRepository(log)
	summaryService := NewSummaryService(simpleDatabaseMaster, simpleDatabaseSummary, summaryRepository)
	service := NewService(transactionService, summaryService)
	return service
}

// injector.go:

var studentAndLecturer = wire.NewSet(NewStudentRepository, NewLecturerRepository)

var databaseMaster = wire.NewSet(NewDatabaseMaster)

var databaseTransaction = wire.NewSet(NewDatabaseTransaction)

var databaseSummary = wire.NewSet(NewDatabaseSummary)

var transaction = wire.NewSet(NewTransactionRepository, NewTransactionService)

var summary = wire.NewSet(NewSummaryRepository, NewSummaryService)
