// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package run_wire

import (
	"github.com/go-playground/validator"
	"github.com/google/wire"
	"net/http"
	"restful-api/app"
	"restful-api/controller"
	"restful-api/middleware"
	"restful-api/repository"
	"restful-api/server"
	"restful-api/service"
)

// Injectors from category_injector.go:

func InitializedCategoryServer() *http.Server {
	db := app.Database()
	categoryRepositoryImpl := repository.NewCategoryRepository()
	validate := validator.New()
	categoryServiceImpl := service.NewCategoryService(db, categoryRepositoryImpl, validate)
	categoryControllerImpl := controller.NewCategoryController(categoryServiceImpl)
	router := app.CategoryRouter(categoryControllerImpl)
	categoryMiddleware := middleware.NewCategoryMiddleware(router)
	httpServer := server.NewCategoryServer(categoryMiddleware)
	return httpServer
}

// category_injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, wire.Bind(new(repository.CategoryRepository), new(*repository.CategoryRepositoryImpl)), service.NewCategoryService, wire.Bind(new(service.CategoryService), new(*service.CategoryServiceImpl)), controller.NewCategoryController, wire.Bind(new(controller.CategoryController), new(*controller.CategoryControllerImpl)))
