// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple2

// Injectors from injector.go:

func InitializeUser() (*UserController, error) {
	userRepository := NewUserRepository()
	userService := NewUserService(userRepository)
	userController, err := NewUserController(userService)
	if err != nil {
		return nil, err
	}
	return userController, nil
}

func InitializeCategory() (CategoryController, error) {
	categoryRepository := NewCategoryRepository()
	categoryService := NewCategoryService(categoryRepository)
	categoryController, err := NewCategoryController(categoryService)
	if err != nil {
		return nil, err
	}
	return categoryController, nil
}