// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

// Injectors from injector.go:

func InitializedCategoryClass() *CategoryClass {
	category := NewCategory()
	class := NewClass()
	categoryClass := &CategoryClass{
		Category: category,
		Class:    class,
	}
	return categoryClass
}

func InitializedDatabase() *DatabaseRepository {
	databasePostgreSQL := NewDatabasePostgreSQL()
	databaseMySQL := NewDatabaseMySQL()
	databaseOracle := NewDatabaseOracle()
	databaseRepository := &DatabaseRepository{
		pg:     databasePostgreSQL,
		mysql:  databaseMySQL,
		oracle: databaseOracle,
	}
	return databaseRepository
}
